# Generated by Django 4.2.14 on 2026-05-08 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_changed', models.CharField(choices=[('status', 'Estado'), ('priority', 'Prioridad'), ('assigned_to', 'Asignado a')], max_length=20, verbose_name='Campo modificado')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='Valor anterior')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='Valor nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Historial de tarea',
                'verbose_name_plural': 'Historial de tareas',
                'ordering': ['-changed_at'],
            },
        ),
    ]
