# Generated by Django 6.0.3 on 2026-05-29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de crédito'), ('prestamo', 'Préstamo')], max_length=20)),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre o referencia del producto (ej. Visa Oro).', max_length=120)),
                ('cupo', models.DecimalField(decimal_places=2, help_text='Límite de crédito o monto del préstamo.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_utilizado', models.DecimalField(decimal_places=2, default=0, help_text='Monto utilizado del cupo.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado')], default='activo', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_financieros', to='banking.cliente')),
            ],
            options={
                'verbose_name': 'Producto financiero',
                'verbose_name_plural': 'Productos financieros',
                'ordering': ['-creado_en'],
            },
        ),
    ]
