# Generated by Django 4.2.29 on 2026-03-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('resourceType', models.CharField(choices=[('sala', 'SALA'), ('equipo', 'EQUIPO'), ('espacio', 'ESPACIO')], max_length=20, null=True)),
                ('description', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('activo', 'ACTIVO'), ('inactivo', 'INACTIVO'), ('mantenimiento', 'MANTENIMIENTO')], max_length=20, null=True)),
                ('availableSchedule', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startAt', models.TimeField()),
                ('endsAt', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('finished', 'Finalizada')], default='requested', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.resource')),
            ],
        ),
    ]
