# Generated by Django 6.0.3 on 2026-04-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_reservation_waitlist_alter_reservation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='miniumTimeToCancel',
            field=models.TimeField(default='01'),
        ),
    ]
