# Generated by Django 6.0.3 on 2026-04-24 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_reservation_miniumtimetocancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='miniumTimeToCancel',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
