# Generated by Django 6.0.3 on 2026-04-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_alter_reservation_miniumtimetocancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='miniumTimeToCancel',
            field=models.IntegerField(default=1),
        ),
    ]
