# Generated by Django 6.0.3 on 2026-04-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_alter_reservation_miniumtimetocancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='miniumTimeToCancel',
        ),
        migrations.AddField(
            model_name='resource',
            name='miniumTimeToCancel',
            field=models.IntegerField(default=1),
        ),
    ]
